env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
overrides:
   -  files:
         - '*.jsx'
         - '*.js'
      rules:
         '@typescript-eslint/no-var-requires': off
         '@typescript-eslint/no-unused-vars': off

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'react/react-in-jsx-scope': "off"
  'react/jsx-props-no-spreading': "off"

  '@typescript-eslint/': "off"

   #  todo: this can go
  '@typescript-eslint/explicit-module-boundary-types': "off"
  'react/jsx-indent-props': "off"
  'react/jsx-filename-extension':
    - 2
    - 'extensions':
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
  'import/no-unresolved': "off"
  'import/extensions': "off"
  'react/jsx-indent': "off"
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 3
  quotes:
    - error
    - single
  no-unused-vars: error
  semi:
    - error
    - never
